<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/05 21:19:23

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=quirofano;host=localhost',
  'username' => 'root',
  'password' => 'mesostel',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
