<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/08 20:24:33

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=Quirofano;host=localhost',
  'username' => 'root',
  'password' => 'ave9201',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
