<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/08/01 14:04:19
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => 'on',
  ),
);
