<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/08/05 19:18:33
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => 'on',
  ),
);
