diferidasSuccess:
 has_layout:     on
 layout:         layout_sn
todosSuccess:
 has_layout:     on
 layout:         layout_sn
showSuccess:
  has_layout:     on
  layout:         layout_sn
busquedaSuccess:
  has_layout:     on
  layout:         layout_sn

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
