propel:
  hc_usuarios:  
    _attributes:          { phpName: User, package: lib.model.data }
    nombre:               { type: varchar(64) }
    pass:                 { type: varchar(64) }
    tipo:                 { type: array }

#Tabla referente a la programacion de cirugias
  hc_agenda:
    _attributes:          { phpName: Agenda, package: lib.model.data }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
#    evento_id:
    programacion:         { type: date }
    fechaestado:     	  { type: date }
    hora:                 { type: time }
    horaestado:           { type: time }
    inicio:               { type: timestamp }
    last_time:            { type: timestamp }
    ingreso:              { type: timestamp }
    sala_id:              { type: integer }
    quirofano_id:         { type: integer }
    egreso:               { type: timestamp }
    cie9mc:               { type: longvarchar }
    cie9mc_id:            { type: varchar(8) }
    cx_realizada:         { type: longvarchar }
    cx_realizada_id:      { type: varchar(8) }
    tipo_cx:              { type: integer }
    diagnostico:          { type: varchar(256) }
    diagnostico_id:       { type: varchar(8) }
    medico_name:          { type: varchar(256) }
    paciente_name:        { type: varchar(256) }
    paciente_id:          { type: integer }
    edad:                 { type: varchar(16) }
    genero:               { type: varchar(16) }
    genero_id:            { type: integer }
    registro:             { type: varchar(16) }
    servicio:             { type: integer }
    #programa:             { type: varchar(256) }
    #programa_id:          { type: integer }
    #realiza:              { type: varchar(256) }
    #realiza_id:           { type: integer }
    #cx_final:             { type: varchar(256) }
    #cx_final_id:          { type: integer }
    #supervisor:           { type: varchar(256) }
    #supervisor_id:        { type: integer }
    #supervisor_final:     { type: varchar(256) }
    #supervisor_final_id:  { type: integer }
    #anestesiologo:        { type: varchar(256) }
    #anestesiologo_id:     { type: integer }
    #anestesiologo_qx:     { type: varchar(256) }
    #anestesiologo_qx_id:        { type: integer }
    #anestesiologo_qx_final:     { type: varchar(256) }
    #anestesiologo_qx_final_id:  { type: integer }
    #maestro_anestesia:          { type: varchar(256) }
    #maestro_anestesia_id:       { type: integer }
    #maestro_anestesia_final:    { type: varchar(256) }
    #maestro_anestesia_final_id: { type: integer }
    anestesia_id:               { type: integer }
    anestesia_empleada:         { type: varchar(256) }
    ev_adversos_anestesia:      { type: longvarchar }
    #instrumentista:             { type: varchar(256) }
    #instrumentista_id:          { type: integer }
    #instrumentista_final:       { type: varchar(256) }
    #instrumentista_final_id:    { type: integer }
    #circulante:                 { type: varchar(256) }
    #circulante_id:              { type: integer }
    #circulante_final:           { type: varchar(256) }
    #circulante_final_id:        { type: integer }
    observaciones:        { type: longvarchar }
    requerimiento:        { type: longvarchar }
    req_insumos:          { type: longvarchar }
    req_hemoderiv:        { type: longvarchar }
    req_laboratorio:      { type: longvarchar }
    req_anestesico:       { type: longvarchar }
    status:               { type: integer, default "1" }
    causa_diferido_id:    { type: integer }
    solicitado:           { type: boolean }
    riesgoqx_id:          { type: integer }
    contaminacionqx_id:   { type: integer }
    eventoqx_id:          { type: integer }
    complicaciones:       { type: longvarchar }
    val_pre_anestesica:   { type: longvarchar }
    reintervencion:       { type: boolean, notnull: true }
    permisos:             { type: object }
    tipo_proc_id:         { type: integer }
    atencion_id:          { type: integer }
    #turno_ci_id:          { type: integer }
    #turno_cf_id:          { type: integer }
    #turno_ii_id:          { type: integer }
    #turno_if_id:          { type: integer }
    tiempo_fuera:         { type: boolean }
    procedencia:          { type: varchar(128) }
    clasificacionqx:      { type: integer }
    region_px:            { type: integer }
    extension_px:         { type: integer }
    anexo_detalle:        { type: integer }
    destino_px:           { type: integer }
    liberacion_sala:      { type: time }
    tiempo_est:           { type: time }
    riesgo_qx_pre:        { type: varchar(256) }
    show_in_index:        { type: boolean, default: true }
    protocolo:            { type: boolean, default: false }
    cancelada:            { type: boolean, default: false }
    created_at:
    updated_at:
    _foreignKeys:
      agenda_sala:
        foreignTable:     siga_sala
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: sala_id, foreign: id }
      agenda_quirofano:
        foreignTable:     siga_quirofano
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: quirofano_id, foreign: id }
#      agenda_cie9mc:
#        foreignTable:     siga_cie9mc
#        onUpdate:         cascade
#        onDelete:         setnull
#        references:
#          - { local: cie9mc_id, foreign: clave }
#      agenda_cx_realizada:
#        foreignTable:     siga_cie9mc
#        onUpdate:         cascade
#        onDelete:         setnull
#        references:
#          - { local: cx_realizada_id, foreign: clave }
#      agenda_diagnostico:
#        foreignTable:     siga_clave
#        onUpdate:         cascade
#        onDelete:         setnull
#        references:
#          - { local: diagnostico_id, foreign: clave }
#      agenda_paciente:
#        foreignTable:     px_paciente
#        onUpdate:         cascade
#        onDelete:         setnull
#        references:
#          - { local: paciente_id, foreign: id }
      #agenda_programa:
      #  foreignTable:     sf_guard_user
      #  onUpdate:         cascade
      #  onDelete:         setnull
      #  references:
      #    - { local: programa_id, foreign: id }
      #agenda_realiza:
      #  foreignTable:     sf_guard_user
      #  onUpdate:         cascade
      #  onDelete:         setnull
      #  references:
      #    - { local: realiza_id, foreign: id }
      #agenda_supervisor:
      #  foreignTable:     sf_guard_user
      #  onUpdate:         cascade
      #  onDelete:         setnull
      #  references:
      #    - { local: supervisor_id, foreign: id }
      #agenda_anestesiologo:
      #  foreignTable:     sf_guard_user
      #  onUpdate:         cascade
      #  onDelete:         setnull
      #  references:
      #    - { local: anestesiologo_id, foreign: id }
#      agenda_anestesia:
#        foreignTable:     siga_tipo_anestesia
#        onUpdate:         cascade
#        onDelete:         setnull
#        references:
#          - { local: anestesia_id, foreign: id }
      #agenda_anestesia_empleada:
      #  foreignTable:     siga_tipo_anestesia
      #  onUpdate:         cascade
      #  onDelete:         setnull
      #  references:
      #    - { local: anestesia_empleada, foreign: id }
     #agenda_instrumentista:
     #  foreignTable:     sf_guard_user
     #  onUpdate:         cascade
     #  onDelete:         setnull
     #  references:
     #    - { local: instrumentista_id, foreign: id }
     #agenda_circulante:
     #  foreignTable:     sf_guard_user
     #  onUpdate:         cascade
     #  onDelete:         setnull
     #  references:
     #     - { local: circulante_id, foreign: id }
      agenda_riesgoqx:
        foreignTable:     siga_riesgoqx
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: riesgoqx_id, foreign: id }
      agenda_contaminacionqx:
        foreignTable:     siga_contaminacionqx
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: contaminacionqx_id, foreign: id }
      agenda_eventoqx:
        foreignTable:     siga_eventoqx
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: eventoqx_id, foreign: id }
      agenda_tipo_proc:
        foreignTable:     siga_procedimiento
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: tipo_proc_id, foreign: id }
      agenda_causa_dif:
        foreignTable:     siga_causa_diferido
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: causa_diferido_id, foreign: id }
      agenda_atencion:
        foreignTable:     siga_atencion
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: atencion_id, foreign: id }
     #agenga_turno_ci:
     #  foreignTable:     siga_turno
     #  onUpdate:         cascade
     #  onDelete:         setnull
     #  references:
     #    - { local: turno_ci_id, foreign: id }
     #agenga_turno_cf:
     #  foreignTable:     siga_turno
     #  onUpdate:         cascade
     #  onDelete:         setnull
     #  references:
     #    - { local: turno_cf_id, foreign: id }
     #agenga_turno_ii:
     #  foreignTable:     siga_turno
     #  onUpdate:         cascade
     #  onDelete:         setnull
     #  references:
     #    - { local: turno_ii_id, foreign: id }
     #agenga_turno_if:
     #  foreignTable:     siga_turno
     #  onUpdate:         cascade
     #  onDelete:         setnull
     #  references:
     #     - { local: turno_if_id, foreign: id }
      agenga_especialidad:
        foreignTable:     siga_especialidad
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: servicio, foreign: id }

  siga_sala_log:
    _attributes:          { phpName: Registrosala, package: lib.model.data }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    sala_id:              { type: integer }
    motivo:               { type: varchar(255) }
    inicio:               { type: timestamp }
    fin:                  { type: timestamp }
    duracion:             { type: varchar(32) }
    _foreignKeys:
#      sala_log:
#        foreignTable:     siga_sala
#        onUpdate:         cascade
#        onDelete:         setnull
#        references:
#          - { local: sala_id, foreign: id }

  hc_agenda_personal:
    _attributes:          { phpName: Personalcirugia, package: lib.model.data }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    personal_id:          { type: integer }
    agenda_id:            { type: integer }
    personal_nombre:      { type: varchar, size: 256 }
#    especialidad_id:
    tipo:                 { type: enum, valueSet: "cirujano, anestesista, enfermeria, otro" }
    status:               { type: integer }
    programa:             { type: boolean }
    inicia:               { type: boolean }
    transoperatorio:      { type: boolean }
    finaliza:             { type: boolean }
    turno:                { type: integer }
    created_at:
    _foreignKeys:
      agenda_personal:
        foreignTable:     hc_agenda
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: agenda_id, foreign: id }
      agenda_personal_id:
        foreignTable:     sf_guard_user
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: personal_id, foreign: id }

  hc_agenda_diagnosticos:
    _attributes:          { phpName: Diagnosticocirugia, package: lib.model.data }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    agenda_id:
    diagnostico_cie10:    { type: varchar, size: 256 }
    diagnostico_id:       { type: varchar, size: 8 }
    tipo_diagnostico:     { type: integer }
    created_at:
#   _foreignKeys:
#      agenda_diagnosticos:
#        foreignTable:     siga_clave
#        onUpdate:         cascade
#        onDelete:         setnull
#        references:
#          - { local: diagnostico_id, foreign: clave }

  hc_agenda_procedimientos:
    _attributes:          { phpName: Procedimientocirugia, package: lib.model.data }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    agenda_id:
    cie9mc:               { type: varchar, size: 256 }
    cie9mc_id:            { type: varchar, size: 8 }
    region:               { type: integer }
    detalles:             { type: varchar, size 256 }
    servicio_id:          { type: integer }
    created_at:
    _foreignKeys:
      agenda_procedimientos:
        foreignTable:     siga_cie9mc
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: cie9mc_id, foreign: clave }
      agenda_procedimientos:
        foreignTable:     siga_especialidad
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: servicio_id, foreign: id }

  hc_agenda_regrogramar:
    _attributes:          { phpName: Procedimientregrogramado, package: lib.model.data }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    agenda_id:            { type: integer }
    programacion:         { type: date }
    hora:                 { type: time }
    sala_id:              { type: integer }
    tiempo_est:           { type: time }
    created_at:
    _foreignKeys:
      agenda_reprogramar:
        foreignTable:     hc_agenda
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: agenda_id, foreign: id }


#Tablas que guardan informacion de los quirofanos y salas
  siga_quirofano:
    _attributes:          { phpName: Quirofano, package: lib.model.config }
    _propel_behaviors:
      sluggable:
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    nombre:               { type: varchar(128), required: true, primaryString: true }
    activo:               { type: boolean, default: true }
    ambulatorio:          { type: boolean }
    permisos:             { type: object }
    created_at:
    updated_at:

  siga_sala:
    _attributes:          { phpName: Salaquirurgica, package: lib.model.config }
    _propel_behaviors:
      sluggable:
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    nombre:               { type: varchar(128), required: true, primaryString: true }
    activo:               { type: boolean }
    bloqueado:            { type: boolean }
    quirofano_id:         { type: integer }
    activo:               { type: boolean, default: true }
    permisos:             { type: object }
    created_at:
    updated_at:
    _foreignKeys:
      sala_quirofano:
        foreignTable:     siga_quirofano
        onUpdate:         cascade
        onDelete:         setnull
        references:
          - { local: quirofano_id, foreign: id }
#Tabla que guarda los turnos laborales
  siga_turno:
    _attributes:          { phpName: Turno, package: lib.model.config }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    nombre:               { type: varchar(128), required: true }
    created_at:
    updated_at:
#tabla de los procedimiento

  siga_procedimiento:
    _attributes:          { phpName: Procedimiento, package: lib.model.config }
    _propel_behaviors:
      sluggable:
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    nombre:               { type: varchar(128), required: true, primaryString: true }
    activo:               { type: boolean, default: true }
    created_at:
    updated_at:

# Causas por las que se difiere la cx
  siga_causa_diferido:
    _attributes:          { phpName: Causadiferido, package: lib.model.config }
    _propel_behaviors:
      nested_set:         { use_scope: true }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    codigo:               { type: varchar(5), required: true  }
    nombre:               { type: varchar(128), required: true, primaryString: true }
    activo:               { type: boolean, default: true }
    created_at:
    updated_at:

# Especialidades medicas - Esquema anidado que almacena las especialidades troncales y ademas las
# subespecialidades
  siga_especialidad:
    _attributes:        { phpName: Especialidad, package: lib.model.config }
    id:                 ~
    nombre:             { type: varchar, size: 64, primaryString: true }
    medica:             { type: boolean, default: true }
    quirurgica:         { type: boolean, default: true }
    activo:             { type: boolean, default: true }
    created_at:
    _propel_behaviors:
      nested_set:       { use_scope: true }

# tipos de procedimiento quirurgico
  siga_atencion:
    _attributes:          { phpName: Atencion, package: lib.model.config }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    nombre:               { type: varchar(128), required: true, primaryString: true }
    activo:               { type: boolean, default: true }
    created_at:
    updated_at:

# Claves de procedimientos del CIE9mc
# Almacena las claves de procedimientos y sus descripciones
  siga_cie9mc:
    _attributes:        { phpName: Cie09mc, package: lib.model.config }
    clave:              { type: varchar(8), required: true, primaryKey: true }
    descripcion:        { type: longvarchar, required: true }
    created_at:
    updated_at:


#Tablas que guardan los diferentes tipos de clasificacion en las cirugias
  siga_riesgoqx:
    _attributes:          { phpName: Riesgoqx, package: lib.model.config }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    nombre:               { type: varchar(128), required: true, primaryString: true}
    descripcion:          { type: longvarchar }
    activo:               { type: boolean, default: true }

  siga_contaminacionqx:
    _attributes:          { phpName: Contaminacionqx, package: lib.model.config }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    nombre:               { type: varchar(128), required: true, primaryString: true }
    descripcion:          { type: longvarchar }
    activo:               { type: boolean, default: true }

  siga_eventoqx:
    _attributes:          { phpName: Eventoqx, package: lib.model.config }
    id:                   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    nombre:               { type: varchar(128), required: true, primaryString: true }
    descripcion:          { type: longvarchar }
    activo:               { type: boolean, default: true }

