<?php



/**
 * Skeleton subclass for representing a row from the 'hc_agenda' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Wed Jul 17 10:47:20 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model.data
 */
class Agenda extends BaseAgenda
{
 /* doSave
  * Extiende el metodo doSave para asignar la fecha de programacion y modificar la hora del ultimo
  * acceso a la cirugia
  * @autor: Antonio Sánchez Uresti
  * @date:  2013-08-02
  */
  public function doSave(PropelPDO $con) 
  {
    switch ($this->getStatus()) {
      case '1':
        $v = strtotime($this->getProgramacion().''.$this->getHora());
        $this->setLastTime($v);
        $this->setInicio($v);
        break;
      case '2':
        $this->setLastTime($this->getIngreso());
        break;
    }
    return parent::doSave($con);
  }
  
}
