<?php



/**
 * Skeleton subclass for representing a row from the 'siga_atencion' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Wed Nov  6 09:55:07 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model.config
 */
class Atencion extends BaseAtencion
{
}
