<?php



/**
 * Skeleton subclass for performing query and update operations on the 'siga_especialidad' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Dec  2 09:45:12 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model.config
 */
class EspecialidadQuery extends BaseEspecialidadQuery
{
}
